### ISSUE TITLE
插件启动报错

### ISSUE THREAD

**Issue by ElainaFanBoy** [RandomEnch/nonebot_plugin_makemidi#1]
pip依赖和fluidsynth已经安装配置，
ModuleNotFoundError: No module named 'midi2audio'

**Comment by RandomEnch** [comment]
少写个依赖，已经更改，请使用pip install midi2audio手动安装midi2audio库，或者pip install --upgrade nonebot_plugin_makemidi更新插件

**Comment by ElainaFanBoy** [comment]
> 少写个依赖，已经更改，请使用pip install midi2audio手动安装midi2audio库，或者pip install --upgrade nonebot_plugin_makemidi更新插件

已解决！（大佬辛苦了qaq）
