### ISSUE TITLE
编曲失败，参数错误

### ISSUE THREAD

**Issue by ElainaFanBoy** [RandomEnch/nonebot_plugin_makemidi#2]
启动没报错，发送编曲后显示
编曲失败，参数错误：
[Errno 2] No such file or directory: 'xxxx\\src\\plugins\\nonebot_plugin_makemidi\\resources\\midi\\QQ号.mid'

**Comment by RandomEnch** [comment]
新版本中更改了储存方式，在插件resources文件夹下新建midi文件夹即可

**Comment by ElainaFanBoy** [comment]
> 新版本中更改了储存方式，在插件resources文件夹下新建midi文件夹即可

感谢，已解决，辛苦了！
