### ISSUE TITLE
编曲失败，参数错误

### ISSUE THREAD

**Issue by shiikai** [RandomEnch/nonebot_plugin_makemidi#6]
发送谱子之后就是
编曲失败，参数错误：[Errno 2] No such file or directory:'xxxx\\nonebot_plugin_makemidi\\resources\\midi\\qq号.wav'

**Comment by RandomEnch** [comment]
检查插件resources文件夹下有无midi文件夹，没有请手动新建文件夹

**Comment by shiikai** [comment]
> 检查插件resources文件夹下有无midi文件夹，没有请手动新建文件夹

本来就有啊，问题是最后路径是wav

**Comment by RandomEnch** [comment]
可以参考 #4 先排查是否正确配置了环境
