### ISSUE TITLE
三个音乐方面的bug

### ISSUE THREAD

**Issue by Pochinki98** [RandomEnch/nonebot_plugin_makemidi#8]
如题
以编曲 2 160 C 6- 1 2. 2. 3 3~ 0 3 5 6 2 1 3. 0_  6- 1 2. 2. 3 3~ 0 3 4 3 2 1 1. 0_ 6- 1 2. 2. 3 3~ 0 3 5 6 2 1 3. 0_ 6- 1 4~ 3~ 2~ 1~ 2 2_ 3_ 6- 5- 6- 0 为例子（千本樱）

当转D调（把C换成D，在钢琴上是是移动两个琴键）会出现两个问题：
<strong>1、插件会转换休止符</strong>
比如简谱，从音调上，D大调的1(do)=C大调的2(re)，若钢琴C大调变到D大调，从键位来看是向右移两个钢琴键；
经过测试，D大调的0=D大调的7=等于C大调的1#，即相当于插件在其他调或把0识别为了7-，然后向右移了两个键？？？
<strong>2、升八度/降八度有错</strong>
问题1已出现此问题，即D大调的7-奇怪地需要被打作D大调的7才能正确发音，原因不明。
——————问题3与音调无关哈——————
<strong>3、节拍不太对</strong>
理论上BPM=10的情况下应该是一拍6秒才对，实测一拍45秒；
经多次测定，发现在设定BPM增大的情况下，实际节拍增加要远快于设定的BPM的增加。
他俩关系有点像这样（当然数据是乱写的）：
<img src="https://img1.imgtp.com/2023/07/27/8MLU8PqT.png">
蓝线是设定的BPM，红线是实际的节拍。

谨启

**Comment by RandomEnch** [comment]
前两个修了，最后一个我也不知道什么原因，可能是mido的问题

**Comment by RandomEnch** [comment]
重构了代码，已修复此问题
